platforms:
  - type: GKE
    launch_stage: HIDDEN
    detections:
      - characteristic_metric:
          metric_type: prometheus.googleapis.com/jenkins_health_check_score/gauge
    exporter_metadata:
      name: Jenkins Prometheus Exporter
      doc_url: https://plugins.jenkins.io/prometheus/
      minimum_supported_version: "2.0.11"
    default_metrics:
      - name: prometheus.googleapis.com/jenkins_health_check_score/gauge
        prometheus_name: jenkins_health_check_score
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/jenkins_executor_in_use_value/gauge
        prometheus_name: jenkins_executor_in_use_value
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/jenkins_node_offline_value/gauge
        prometheus_name: jenkins_node_offline_value
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/jenkins_executor_free_value/gauge
        prometheus_name: jenkins_executor_free_value
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/jenkins_plugins_failed/gauge
        prometheus_name: jenkins_plugins_failed
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/vm_memory_total_max/gauge
        prometheus_name: vm_memory_total_max
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/vm_memory_total_used/gauge
        prometheus_name: vm_memory_total_used
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/jenkins_job_building_duration/summary
        prometheus_name: jenkins_job_building_duration
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/jenkins_queue_size_value/gauge
        prometheus_name: jenkins_queue_size_value
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/jenkins_job_queuing_duration_count/summary
        prometheus_name: jenkins_job_queuing_duration_count
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/vm_cpu_load/gauge
        prometheus_name: vm_cpu_load
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/jenkins_job_queuing_duration/summary
        prometheus_name: jenkins_job_queuing_duration
        kind: GAUGE
        value_type: DOUBLE
    install_documentation_url: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/jenkins
