platforms:
  - type: GKE
    detections:
      - characteristic_metric:
          metric_type: prometheus.googleapis.com/couchdb_httpd_open_os_files/gauge
    launch_stage: GA
    exporter_metadata:
      name: CouchDB Prometheus Exporter
      doc_url: https://github.com/gesellix/couchdb-prometheus-exporter
      minimum_supported_version: v30.4.3
    default_metrics:
      - name: prometheus.googleapis.com/couchdb_httpd_request_methods/gauge
        prometheus_name: couchdb_httpd_request_methods
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/couchdb_httpd_status_codes/gauge
        prometheus_name: couchdb_httpd_status_codes
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/couchdb_httpd_request_time/gauge
        prometheus_name: couchdb_httpd_request_time
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/couchdb_httpd_bulk_requests/gauge
        prometheus_name: couchdb_httpd_bulk_requests
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/couchdb_httpd_view_reads/gauge
        prometheus_name: couchdb_httpd_view_reads
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/couchdb_httpd_database_reads/gauge
        prometheus_name: couchdb_httpd_database_reads
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/couchdb_httpd_database_writes/gauge
        prometheus_name: couchdb_httpd_view_reads
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/couchdb_httpd_open_os_files/gauge
        prometheus_name: couchdb_httpd_open_os_files
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/couchdb_httpd_open_databases/gauge
        prometheus_name: couchdb_httpd_open_databases
        kind: GAUGE
        value_type: DOUBLE
    install_documentation_url: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/couchdb
