platforms:
  - type: GKE
    detections:
      - characteristic_metric:
          metric_type: prometheus.googleapis.com/mysql_up/gauge
    launch_stage: GA
    exporter_metadata:
      name: MySQL Prometheus Exporter
      doc_url: https://github.com/prometheus/mysqld_exporter
      minimum_supported_version: v0.14.0
    default_metrics:
      - name: prometheus.googleapis.com/mysql_global_status_uptime/unknown:counter
        prometheus_name: mysql_global_status_uptime
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_up/gauge
        prometheus_name: mysql_up
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_threads_connected/unknown:counter
        prometheus_name: mysql_global_status_threads_connected
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_variables_max_connections/gauge
        prometheus_name: mysql_global_variables_max_connections
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_connection_errors_total/counter
        prometheus_name: mysql_global_status_connection_errors_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_variables_open_files_limit/gauge
        prometheus_name: mysql_global_variables_open_files_limit
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_variables_innodb_open_files/gauge
        prometheus_name: mysql_global_variables_innodb_open_files
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_slow_queries/unknown:counter
        prometheus_name: mysql_global_variables_innodb_open_files
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_table_open_cache_hits/unknown:counter
        prometheus_name: mysql_global_status_table_open_cache_hits
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_table_open_cache_misses/unknown:counter
        prometheus_name: mysql_global_status_table_open_cache_misses
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_innodb_buffer_pool_read_requests/unknown:counter
        prometheus_name: mysql_global_status_innodb_buffer_pool_read_requests
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_innodb_buffer_pool_reads/unknown:counter
        prometheus_name: mysql_global_status_innodb_buffer_pool_reads
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_select_full_join/unknown:counter
        prometheus_name: mysql_global_status_select_full_join
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_select_full_range_join/unknown:counter
        prometheus_name: mysql_global_status_select_full_range_join
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_select_range_check/unknown:counter
        prometheus_name: mysql_global_status_select_range_check
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_select_scan/unknown:counter
        prometheus_name: mysql_global_status_select_scan
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_commands_total/unknown:counter
        prometheus_name: mysql_global_status_commands_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_questions/unknown:counter
        prometheus_name: mysql_global_status_questions
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_innodb_data_fsyncs/unknown:counter
        prometheus_name: mysql_global_status_innodb_data_fsyncs
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_innodb_buffer_pool_reads/unknown:counter
        prometheus_name: mysql_global_status_innodb_buffer_pool_reads
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/mysql_global_status_innodb_buffer_pool_read_requests/unknown:counter
        prometheus_name: mysql_global_status_innodb_buffer_pool_read_requests
        kind: CUMULATIVE
        value_type: DOUBLE
    install_documentation_url: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/mysql
